-- GDR Production Phase 2 migration
-- Apply AFTER schema.sql in the connected Supabase project.

create table if not exists public.datasets (
  id uuid primary key default gen_random_uuid(),
  dataset_code text unique not null,
  project_id uuid references public.projects(id) on delete set null,
  title text not null,
  description text,
  owner_user_id uuid references auth.users(id),
  access_level text not null default 'private' check (access_level in ('private','project','restricted','public')),
  source_provenance text,
  license text,
  repository_url text,
  current_version text,
  sha256 text,
  record_count bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.dataset_versions (
  id uuid primary key default gen_random_uuid(),
  dataset_id uuid not null references public.datasets(id) on delete cascade,
  version text not null,
  sha256 text,
  storage_path text,
  release_notes text,
  created_by uuid references auth.users(id),
  created_at timestamptz not null default now(),
  unique(dataset_id, version)
);

create table if not exists public.research_outputs (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  output_code text unique not null,
  output_type text not null check (output_type in ('manuscript','publication','dataset','software','protocol','preprint','patent','report','visualization','other')),
  title text not null,
  doi text,
  url text,
  citation text,
  status text not null default 'draft' check (status in ('draft','internal_review','submitted','accepted','published','released','archived')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.email_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  recipient text,
  related_entity_type text,
  related_entity_id text,
  provider_message_id text,
  delivery_status text not null default 'queued',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_settings (
  id smallint primary key default 1 check (id = 1),
  organization_name text not null default 'GDR — Global Discovery & Research Network',
  public_site_url text not null default 'https://www.gdrnetwork.org/',
  support_email text,
  research_email text,
  notifications_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);

insert into public.admin_settings (id) values (1) on conflict (id) do nothing;

alter table public.datasets enable row level security;
alter table public.dataset_versions enable row level security;
alter table public.research_outputs enable row level security;
alter table public.email_events enable row level security;
alter table public.admin_settings enable row level security;

create policy "datasets_admin_all" on public.datasets for all using (public.is_gdr_admin()) with check (public.is_gdr_admin());
create policy "datasets_public_read" on public.datasets for select using (access_level = 'public' or public.is_gdr_admin() or owner_user_id = auth.uid() or (project_id is not null and exists (select 1 from public.project_members pm where pm.project_id = datasets.project_id and pm.user_id = auth.uid())));

create policy "dataset_versions_admin_all" on public.dataset_versions for all using (public.is_gdr_admin()) with check (public.is_gdr_admin());
create policy "dataset_versions_member_read" on public.dataset_versions for select using (public.is_gdr_admin() or exists (select 1 from public.datasets d left join public.project_members pm on pm.project_id = d.project_id where d.id = dataset_versions.dataset_id and (d.access_level = 'public' or d.owner_user_id = auth.uid() or pm.user_id = auth.uid())));

create policy "outputs_admin_all" on public.research_outputs for all using (public.is_gdr_admin()) with check (public.is_gdr_admin());
create policy "outputs_member_read" on public.research_outputs for select using (public.is_gdr_admin() or status in ('published','released') or exists (select 1 from public.project_members pm where pm.project_id = research_outputs.project_id and pm.user_id = auth.uid()));

create policy "email_events_admin_read" on public.email_events for select using (public.is_gdr_admin());
create policy "admin_settings_admin_all" on public.admin_settings for all using (public.is_gdr_admin()) with check (public.is_gdr_admin());

-- Audit helpers
create or replace function public.log_gdr_event(p_entity_type text, p_entity_id text, p_action text, p_metadata jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path = public as $$
begin
  insert into public.audit_events(actor_user_id, entity_type, entity_id, action, metadata)
  values(auth.uid(), p_entity_type, p_entity_id, p_action, coalesce(p_metadata,'{}'::jsonb));
end;
$$;

-- Useful indexes
create index if not exists idx_research_ideas_status on public.research_ideas(status, created_at desc);
create index if not exists idx_projects_status on public.projects(status, updated_at desc);
create index if not exists idx_datasets_project on public.datasets(project_id, created_at desc);
create index if not exists idx_outputs_project on public.research_outputs(project_id, status);
create index if not exists idx_email_events_created on public.email_events(created_at desc);

-- Security note: founder/admin roles must be assigned only via a trusted server-side/admin process.
-- Never expose the Supabase service_role key or mail-provider API keys in browser JavaScript or public GitHub files.
