-- GDR — Global Discovery & Research Network
-- Supabase/PostgreSQL production starter schema.
-- Apply in a dedicated Supabase project after reviewing governance and privacy requirements.

create extension if not exists pgcrypto;

create type public.gdr_role as enum ('researcher','reviewer','project_lead','domain_chair','admin','founder');

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null,
  title text,
  institution text,
  country text,
  orcid text,
  primary_discipline text,
  specializations text,
  methods text,
  collaboration_interests text,
  role public.gdr_role not null default 'researcher',
  verified boolean not null default false,
  public_profile boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.research_ideas (
  id uuid primary key default gen_random_uuid(),
  submitted_by uuid not null references auth.users(id) on delete cascade,
  title text not null,
  primary_domain text not null,
  research_gap text not null,
  multidisciplinary_need text not null,
  status text not null default 'submitted' check (status in ('submitted','screening','needs_revision','approved','merged','rejected')),
  private_submission boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.discovery_challenges (
  id uuid primary key default gen_random_uuid(),
  public_id text unique not null,
  title text not null,
  summary text not null,
  research_gap text not null,
  hypothesis text,
  disciplines text[] not null default '{}',
  expertise_needed text[] not null default '{}',
  expected_outputs text[] not null default '{}',
  status text not null default 'concept_development' check (status in ('concept_development','open','team_formation','active','validation','completed','paused')),
  lead_user_id uuid references auth.users(id),
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.applications (
  id uuid primary key default gen_random_uuid(),
  challenge_id uuid not null references public.discovery_challenges(id) on delete cascade,
  researcher_id uuid not null references auth.users(id) on delete cascade,
  proposed_role text not null,
  contribution text not null,
  status text not null default 'submitted' check (status in ('submitted','under_review','shortlisted','accepted','declined','withdrawn')),
  created_at timestamptz not null default now(),
  unique(challenge_id, researcher_id)
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  challenge_id uuid references public.discovery_challenges(id),
  project_code text unique not null,
  title text not null,
  status text not null default 'planning' check (status in ('planning','protocol','active','analysis','validation','manuscript','completed','paused')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.project_members (
  project_id uuid references public.projects(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  project_role text not null,
  credit_roles text[],
  joined_at timestamptz not null default now(),
  primary key (project_id, user_id)
);

create table if not exists public.milestones (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  title text not null,
  due_date date,
  status text not null default 'planned' check (status in ('planned','active','blocked','completed')),
  notes text
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.is_gdr_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (
    select 1 from public.profiles p
    where p.user_id = auth.uid() and p.role in ('admin','founder')
  );
$$;

alter table public.profiles enable row level security;
alter table public.research_ideas enable row level security;
alter table public.discovery_challenges enable row level security;
alter table public.applications enable row level security;
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.milestones enable row level security;
alter table public.audit_events enable row level security;

create policy "profiles_self_read" on public.profiles for select using (auth.uid() = user_id or public_profile = true or public.is_gdr_admin());
create policy "profiles_self_insert" on public.profiles for insert with check (auth.uid() = user_id);
create policy "profiles_self_update" on public.profiles for update using (auth.uid() = user_id or public.is_gdr_admin()) with check (auth.uid() = user_id or public.is_gdr_admin());

create policy "ideas_owner_insert" on public.research_ideas for insert with check (auth.uid() = submitted_by);
create policy "ideas_owner_read" on public.research_ideas for select using (auth.uid() = submitted_by or public.is_gdr_admin());
create policy "ideas_owner_update" on public.research_ideas for update using (auth.uid() = submitted_by or public.is_gdr_admin());

create policy "public_challenges_read" on public.discovery_challenges for select using (is_public = true or public.is_gdr_admin() or auth.uid() = lead_user_id);
create policy "challenges_admin_write" on public.discovery_challenges for all using (public.is_gdr_admin()) with check (public.is_gdr_admin());

create policy "applications_owner_insert" on public.applications for insert with check (auth.uid() = researcher_id);
create policy "applications_owner_read" on public.applications for select using (auth.uid() = researcher_id or public.is_gdr_admin());
create policy "applications_admin_update" on public.applications for update using (public.is_gdr_admin() or auth.uid() = researcher_id);

create policy "projects_member_read" on public.projects for select using (public.is_gdr_admin() or exists (select 1 from public.project_members pm where pm.project_id = id and pm.user_id = auth.uid()));
create policy "projects_admin_write" on public.projects for all using (public.is_gdr_admin()) with check (public.is_gdr_admin());

create policy "project_members_read" on public.project_members for select using (public.is_gdr_admin() or user_id = auth.uid() or exists (select 1 from public.project_members pm2 where pm2.project_id = project_id and pm2.user_id = auth.uid()));
create policy "project_members_admin_write" on public.project_members for all using (public.is_gdr_admin()) with check (public.is_gdr_admin());

create policy "milestones_project_member_read" on public.milestones for select using (public.is_gdr_admin() or exists (select 1 from public.project_members pm where pm.project_id = project_id and pm.user_id = auth.uid()));
create policy "milestones_admin_write" on public.milestones for all using (public.is_gdr_admin()) with check (public.is_gdr_admin());

create policy "audit_admin_read" on public.audit_events for select using (public.is_gdr_admin());

-- Important: assign founder/admin roles only through a trusted server-side/admin process.
-- Do not expose the Supabase service_role key in GitHub Pages.
