const SUPABASE_URL='https://klwzkmfzxrikqslkclik.supabase.co';
const SUPABASE_KEY='sb_publishable_PeoU1Z8jnXXptuck9Zb_Jg_QEeBLZKm';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);

const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const NS='http://www.w3.org/2000/svg';

const palettes={biomedical:['#123A63','#3D7EA6','#2A8C82','#A8DADC','#F7FAFC'],molecular:['#344EAD','#7A5AF8','#2FB7C4','#E9EEF5','#1F2937'],immune:['#214E7A','#1F8A70','#D9A441','#C96A7B','#F8FAFC'],cancer:['#2B2D42','#B84A62','#7B4F8C','#D6B98C','#F3F4F6'],eco:['#2F6B4F','#67A65B','#9B7653','#4C93B6','#EFF6EE'],data:['#23395B','#3D77A8','#3EA7A3','#D98C3F','#F6F8FB'],physics:['#203864','#4472C4','#5B9BD5','#A5A5A5','#F2F2F2'],chemistry:['#243B53','#3C8DAD','#E0A458','#A23B72','#F7F7F7']};
const domains={biological:['Cell','Nucleus','Mitochondrion','DNA','Protein','Receptor','Virus','Bacterium'],chemical:['Molecule','Atom','Bond','Reaction','Flask','Beaker','Crystal','Catalyst'],physical:['Force','Wave','Lens','Circuit','Magnet','Photon','Field','Vector'],mathematical:['Equation','Function','Matrix','Graph','Axis','Probability','Geometry','Model'],bioinformatics:['DNA sequence','Database','Pipeline','Network','Heatmap','Model','Server','Genome']};
const layouts={'Graphical Abstract':['Context / research problem','Central mechanism or intervention','Main result / conclusion'],'Mechanism Figure':['Upstream trigger','Core molecular/cellular mechanism','Downstream biological effect'],'Experimental Workflow':['Samples / inputs','Experimental or computational methods','Analysis and validation'],'Bioinformatics Pipeline':['Data acquisition','Preprocessing / modelling','Interpretation / validation'],'Clinical Pathway':['Patient / cohort','Assessment / intervention','Decision / outcome'],'Mathematical Model':['Variables / assumptions','Model / equations','Simulation / inference / outcome']};

let history=[], currentUser=null, currentProfile=null, isAdmin=false, selected=null, drag=null, currentProjectId=null;
const canvas=$('#figureCanvas');

/* ---------- V0.3 UI ENHANCEMENTS ---------- */
const v03style=document.createElement('style');
v03style.textContent=`
.sf-object{cursor:move}.sf-object.selected>.selection-outline{display:block}.selection-outline{display:none;fill:none;stroke:#2f80ed;stroke-width:4;stroke-dasharray:10 8;vector-effect:non-scaling-stroke;pointer-events:none}.object-tools{display:grid;grid-template-columns:1fr 1fr;gap:7px}.object-tools button,.project-tools button{border:1px solid #d4dde6;background:#fff;border-radius:9px;padding:8px;font-size:11px;font-weight:800;cursor:pointer}.object-tools button.danger{color:#9a3246;background:#fff4f5}.project-list{display:grid;gap:7px;max-height:190px;overflow:auto}.project-row{display:grid;grid-template-columns:1fr auto;gap:7px;align-items:center;border:1px solid #dbe2ea;background:#fff;border-radius:9px;padding:8px}.project-row button{border:0;background:#edf4ff;color:#234d80;border-radius:7px;padding:6px 8px;font-weight:800;cursor:pointer}.starter-assets{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.starter-assets button{border:1px solid #d4dde6;background:#fff;border-radius:10px;padding:9px 6px;font-size:11px;font-weight:800;cursor:pointer}.selected-note{font-size:11px;color:#667085;background:#fff;border:1px solid #e0e6ed;border-radius:9px;padding:8px}.export-grid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.export-grid button{border:1px solid #cfd8e3;background:#fff;border-radius:9px;padding:8px;font-size:11px;font-weight:800;cursor:pointer}
`;
document.head.appendChild(v03style);

function enhanceRails(){
 const left=$('.left-rail'), right=$('.right-rail');
 const starters=document.createElement('div');starters.className='rail-block';starters.innerHTML=`<b>Starter vector assets</b><div class="starter-assets"><button data-starter="cell">Cell</button><button data-starter="mitochondrion">Mitochondrion</button><button data-starter="dna">DNA</button><button data-starter="virus">Virus</button><button data-starter="molecule">Molecule</button><button data-starter="flask">Flask</button><button data-starter="atom">Atom</button><button data-starter="wave">Wave</button><button data-starter="graph">Graph</button><button data-starter="database">Database</button><button data-starter="network">Network</button><button data-starter="heatmap">Heatmap</button></div>`;
 left.appendChild(starters);
 const objects=document.createElement('div');objects.className='rail-block';objects.innerHTML=`<b>Selected object</b><div class="selected-note" id="selectedNote">Select an object on the canvas.</div><label>Scale<input id="objectScale" type="range" min="40" max="220" value="100"></label><div class="object-tools"><button id="recolorObject">Apply colors</button><button id="duplicateObject">Duplicate</button><button id="frontObject">Bring front</button><button id="backObject">Send back</button><button id="deleteObject" class="danger">Delete</button><button id="deselectObject">Deselect</button></div>`;
 right.prepend(objects);
 const projects=document.createElement('div');projects.className='rail-block';projects.innerHTML=`<b>My projects</b><button class="btn small" id="refreshProjects">Refresh saved projects</button><div id="projectList" class="project-list"><small>Sign in to view saved projects.</small></div>`;right.appendChild(projects);
 const exports=document.createElement('div');exports.className='rail-block';exports.innerHTML=`<b>Export</b><div class="export-grid"><button id="exportSvg">SVG vector</button><button id="exportPng">PNG 2×</button></div><small>SVG remains fully scalable. PNG exports at 3200 × 2000 pixels from the current 1600 × 1000 canvas.</small>`;right.appendChild(exports);
 $$('[data-starter]').forEach(b=>b.onclick=()=>addStarter(b.dataset.starter));
 $('#recolorObject').onclick=()=>recolorSelected();$('#duplicateObject').onclick=()=>duplicateSelected();$('#frontObject').onclick=()=>bringFront();$('#backObject').onclick=()=>sendBack();$('#deleteObject').onclick=()=>deleteSelected();$('#deselectObject').onclick=()=>selectObject(null);$('#objectScale').oninput=e=>scaleSelected(+e.target.value/100);$('#refreshProjects').onclick=loadProjects;$('#exportSvg').onclick=exportSVG;$('#exportPng').onclick=exportPNG;
}

enhanceRails();

/* ---------- SVG HELPERS + OBJECT MODEL ---------- */
function svgEl(tag,attrs={}){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
function snapshot(){history.push(canvas.innerHTML);if(history.length>40)history.shift()}
function nextPos(){const n=canvas.querySelectorAll('.sf-object').length;return {x:160+(n%6)*120,y:150+(n%5)*95}}
function makeObject(label='object',x=200,y=180){const g=svgEl('g',{'class':'sf-object','data-kind':label,'data-x':x,'data-y':y,'data-scale':'1',transform:`translate(${x} ${y}) scale(1)`});return g}
function outline(x,y,w,h){return svgEl('rect',{class:'selection-outline',x,y,width:w,height:h,rx:10})}
function updateTransform(g){const x=+(g.dataset.x||0),y=+(g.dataset.y||0),s=+(g.dataset.scale||1);g.setAttribute('transform',`translate(${x} ${y}) scale(${s})`)}
function selectObject(g){if(selected)selected.classList.remove('selected');selected=g;if(selected){selected.classList.add('selected');$('#selectedNote').textContent=`Selected: ${selected.dataset.kind||'object'}`;$('#objectScale').value=Math.round((+(selected.dataset.scale||1))*100)}else{$('#selectedNote').textContent='Select an object on the canvas.'}}
function addToCanvas(g){snapshot();canvas.appendChild(g);selectObject(g)}

function addText(text='Scientific label',x=180,y=180){const g=makeObject('text',x,y);const t=svgEl('text',{x:0,y:0,fill:$('#elementColor').value,'font-size':42,'font-family':'Arial, sans-serif','font-weight':600,'data-colorable':'fill'});t.textContent=text;g.append(t,outline(-15,-55,Math.max(180,text.length*25),75));addToCanvas(g)}
function ensureArrowMarker(){let defs=canvas.querySelector('defs[data-sf-defs]');if(!defs){defs=svgEl('defs',{'data-sf-defs':'1'});canvas.insertBefore(defs,canvas.firstChild)}let marker=defs.querySelector('#sfArrow');if(!marker){marker=svgEl('marker',{id:'sfArrow',markerWidth:12,markerHeight:8,refX:11,refY:4,orient:'auto',markerUnits:'strokeWidth'});const p=svgEl('path',{d:'M0,0 L12,4 L0,8 z',fill:'#24557a','data-marker-color':'1'});marker.appendChild(p);defs.appendChild(marker)}return marker}
function addShape(kind){const p=nextPos(),g=makeObject(kind,p.x,p.y),c=$('#elementColor').value,a=$('#accentColor').value,w=$('#lineWidth').value;if(kind==='box'||kind==='label'){g.append(svgEl('rect',{x:0,y:0,width:360,height:170,rx:kind==='label'?35:16,fill:kind==='label'?'#ffffff':a+'33',stroke:c,'stroke-width':w,'data-colorable':'stroke','data-accentable':'fill'}),outline(-10,-10,380,190))}else if(kind==='circle'){g.append(svgEl('circle',{cx:110,cy:110,r:105,fill:a+'33',stroke:c,'stroke-width':w,'data-colorable':'stroke','data-accentable':'fill'}),outline(-5,-5,230,230))}else{ensureArrowMarker();const line=svgEl('line',{x1:0,y1:40,x2:400,y2:40,stroke:c,'stroke-width':w,'stroke-linecap':'round','data-colorable':'stroke'});if(kind==='arrow')line.setAttribute('marker-end','url(#sfArrow)');else line.setAttribute('stroke-dasharray','14 10');g.append(line,outline(-10,0,430,85))}addToCanvas(g)}

function starterGroup(kind){const p=nextPos(),g=makeObject(kind,p.x,p.y),c=$('#elementColor').value,a=$('#accentColor').value;const stroke={stroke:c,'stroke-width':5,'stroke-linecap':'round','stroke-linejoin':'round','data-colorable':'stroke'};if(kind==='cell'){g.append(svgEl('ellipse',{cx:130,cy:105,rx:125,ry:95,fill:a+'30',...stroke,'data-accentable':'fill'}),svgEl('circle',{cx:130,cy:105,r:43,fill:a+'66',...stroke,'data-accentable':'fill'}),outline(-10,-10,280,230))}
 else if(kind==='mitochondrion'){g.append(svgEl('path',{d:'M15 75 C25 5 200 0 220 70 C235 125 155 155 75 135 C25 122 5 105 15 75Z',fill:a+'3b',...stroke,'data-accentable':'fill'}),svgEl('path',{d:'M42 76 C65 35 82 116 108 72 C131 33 147 118 177 73 C193 49 201 60 205 72',fill:'none',...stroke}),outline(0,0,240,160))}
 else if(kind==='dna'){const p1=svgEl('path',{d:'M20 0 C150 70 20 140 150 210 C240 260 190 320 80 360',fill:'none',...stroke});const p2=svgEl('path',{d:'M150 0 C20 70 150 140 20 210 C-70 260 -20 320 90 360',fill:'none',stroke:a,'stroke-width':5,'data-accentable':'stroke'});g.append(p1,p2);for(let y=30;y<340;y+=42)g.append(svgEl('line',{x1:48+(y%84?0:45),y1:y,x2:122-(y%84?0:45),y2:y,stroke:'#6b7280','stroke-width':3}));g.append(outline(-35,-10,230,390))}
 else if(kind==='virus'){g.append(svgEl('circle',{cx:105,cy:105,r:68,fill:a+'3b',...stroke,'data-accentable':'fill'}));for(let i=0;i<12;i++){const ang=i*Math.PI/6,x1=105+70*Math.cos(ang),y1=105+70*Math.sin(ang),x2=105+105*Math.cos(ang),y2=105+105*Math.sin(ang);g.append(svgEl('line',{x1,y1,x2,y2,...stroke}),svgEl('circle',{cx:x2,cy:y2,r:10,fill:c,'data-colorable':'fill'}))}g.append(outline(-15,-15,240,240))}
 else if(kind==='molecule'){const pts=[[20,90],[100,30],[185,75],[125,155],[225,165]];pts.forEach((p,i)=>{if(i)g.append(svgEl('line',{x1:pts[i-1][0],y1:pts[i-1][1],x2:p[0],y2:p[1],...stroke}));g.append(svgEl('circle',{cx:p[0],cy:p[1],r:20,fill:i%2?a:c,'data-colorable':'fill','data-accentable':'fill'}))});g.append(outline(-10,0,260,200))}
 else if(kind==='flask'){g.append(svgEl('path',{d:'M80 10 L145 10 M95 10 L95 75 L30 190 Q25 215 60 220 L170 220 Q205 215 198 190 L135 75 L135 10',fill:a+'35',...stroke,'data-accentable':'fill'}),svgEl('path',{d:'M52 166 Q110 145 178 166',fill:'none',stroke:a,'stroke-width':7,'data-accentable':'stroke'}),outline(10,0,210,240))}
 else if(kind==='atom'){g.append(svgEl('circle',{cx:110,cy:100,r:16,fill:c,'data-colorable':'fill'}));[0,60,120].forEach(r=>g.append(svgEl('ellipse',{cx:110,cy:100,rx:100,ry:35,fill:'none',...stroke,transform:`rotate(${r} 110 100)`})));g.append(outline(0,-15,220,230))}
 else if(kind==='wave'){let d='M0 90';for(let x=0;x<=320;x+=10)d+=` L${x} ${90+55*Math.sin(x/32)}`;g.append(svgEl('path',{d,fill:'none',...stroke}),outline(-10,15,350,160))}
 else if(kind==='graph'){g.append(svgEl('line',{x1:20,y1:220,x2:20,y2:10,...stroke}),svgEl('line',{x1:20,y1:220,x2:300,y2:220,...stroke}),svgEl('path',{d:'M25 205 C80 195 80 155 125 160 C165 165 170 95 220 95 C255 95 265 45 295 35',fill:'none',stroke:a,'stroke-width':7,'data-accentable':'stroke'}),outline(0,0,320,245))}
 else if(kind==='database'){g.append(svgEl('ellipse',{cx:110,cy:35,rx:95,ry:30,fill:a+'45',...stroke,'data-accentable':'fill'}),svgEl('rect',{x:15,y:35,width:190,height:145,fill:a+'2a',stroke:'none','data-accentable':'fill'}),svgEl('path',{d:'M15 35 V180 C15 215 205 215 205 180 V35',fill:'none',...stroke}),svgEl('ellipse',{cx:110,cy:180,rx:95,ry:30,fill:'none',...stroke}),outline(0,0,225,225))}
 else if(kind==='network'){const pts=[[35,40],[145,25],[250,70],[80,145],[195,160],[300,145]];[[0,1],[1,2],[0,3],[1,4],[2,5],[3,4],[4,5],[1,3],[2,4]].forEach(([i,j])=>g.append(svgEl('line',{x1:pts[i][0],y1:pts[i][1],x2:pts[j][0],y2:pts[j][1],stroke:'#8996a8','stroke-width':4})));pts.forEach((p,i)=>g.append(svgEl('circle',{cx:p[0],cy:p[1],r:17,fill:i%2?a:c,'data-colorable':'fill','data-accentable':'fill'})));g.append(outline(0,0,330,195))}
 else if(kind==='heatmap'){for(let r=0;r<5;r++)for(let col=0;col<6;col++){const alpha=.18+(r+col)/13;g.append(svgEl('rect',{x:col*42,y:r*42,width:36,height:36,rx:4,fill:col%2?c:a,opacity:alpha,'data-colorable':'fill','data-accentable':'fill'}))}g.append(outline(-8,-8,265,225))}
 return g}
function addStarter(kind){snapshot();const g=starterGroup(kind);canvas.appendChild(g);selectObject(g)}

/* ---------- INTERACTION ---------- */
canvas.addEventListener('pointerdown',e=>{const g=e.target.closest?.('.sf-object');if(!g){if(e.target===canvas||e.target.tagName==='rect'&&e.target.parentNode===canvas)selectObject(null);return}selectObject(g);const pt=svgPoint(e);drag={g,startX:pt.x,startY:pt.y,origX:+g.dataset.x,origY:+g.dataset.y};g.setPointerCapture?.(e.pointerId);snapshot();e.preventDefault()});
canvas.addEventListener('pointermove',e=>{if(!drag)return;const pt=svgPoint(e);drag.g.dataset.x=drag.origX+(pt.x-drag.startX);drag.g.dataset.y=drag.origY+(pt.y-drag.startY);updateTransform(drag.g)});
canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);
function svgPoint(evt){const p=canvas.createSVGPoint();p.x=evt.clientX;p.y=evt.clientY;return p.matrixTransform(canvas.getScreenCTM().inverse())}
function recolorSelected(){if(!selected)return;const c=$('#elementColor').value,a=$('#accentColor').value;selected.querySelectorAll('[data-colorable]').forEach(el=>{const attr=el.dataset.colorable;el.setAttribute(attr,c)});selected.querySelectorAll('[data-accentable]').forEach(el=>{const attr=el.dataset.accentable;const old=el.getAttribute(attr)||'';el.setAttribute(attr,old.length===9?a+'55':a)});ensureArrowMarker().querySelector('[data-marker-color]')?.setAttribute('fill',c)}
function duplicateSelected(){if(!selected)return;snapshot();const clone=selected.cloneNode(true);clone.classList.remove('selected');clone.dataset.x=+selected.dataset.x+45;clone.dataset.y=+selected.dataset.y+45;updateTransform(clone);canvas.appendChild(clone);selectObject(clone)}
function deleteSelected(){if(!selected)return;snapshot();const old=selected;selectObject(null);old.remove()}
function bringFront(){if(!selected)return;snapshot();canvas.appendChild(selected)}
function sendBack(){if(!selected)return;snapshot();const first=[...canvas.children].find(x=>x.classList?.contains('sf-object'));if(first)canvas.insertBefore(selected,first)}
function scaleSelected(v){if(!selected)return;selected.dataset.scale=v;updateTransform(selected)}

/* ---------- EXISTING TOOLS ---------- */
function renderDomain(){const d=$('#studioDomain').value;$('#domainElements').innerHTML=domains[d].map(x=>`<button data-quick="${esc(x)}">${esc(x)}</button>`).join('');$$('[data-quick]').forEach(b=>b.onclick=()=>addText(b.dataset.quick,...Object.values(nextPos())))}
renderDomain();$('#studioDomain').onchange=renderDomain;$$('[data-tool]').forEach(b=>b.onclick=()=>b.dataset.tool==='text'?addText():addShape(b.dataset.tool));
$('#undoBtn').onclick=()=>{if(history.length){canvas.innerHTML=history.pop();selectObject(null);ensureCanvasBase()}};$('#clearCanvas').onclick=()=>{snapshot();canvas.innerHTML='<rect width="1600" height="1000" fill="#ffffff" data-canvas-bg="1"/>';selectObject(null)};
function ensureCanvasBase(){if(!canvas.querySelector('[data-canvas-bg]')){const base=canvas.querySelector('rect');if(base&&base.parentNode===canvas)base.setAttribute('data-canvas-bg','1')}}ensureCanvasBase();

function renderPalette(){const p=palettes[$('#paletteType').value]||palettes.biomedical;$('#paletteOutput').innerHTML=p.map(c=>`<i title="${c}" style="background:${c}"></i>`).join('');$('#elementColor').value=p[0];$('#accentColor').value=p[2]||p[1];if(selected)recolorSelected()}
$('#suggestPalette').onclick=renderPalette;renderPalette();
$('#findAsset').onclick=()=>{const q=$('#studioSearch').value.trim()||$('#studioDomain').value;window.open('https://bioicons.com/','_blank','noopener');setTimeout(()=>window.open('https://smart.servier.com/?s='+encodeURIComponent(q),'_blank','noopener'),150)};

function tokenize(text){return [...new Set(text.toLowerCase().replace(/[^a-z0-9\s-]/g,' ').split(/\s+/).filter(x=>x.length>3))].slice(0,10)}
$('#generatePlan').onclick=()=>{const topic=$('#topic').value.trim();if(!topic){$('#topic').focus();return}const type=$('#figureType').value,field=$('#field').value;let pk='biomedical';if(/bioinformatics/i.test(field))pk='data';else if(/immun/i.test(field))pk='immune';else if(/cancer/i.test(field))pk='cancer';else if(/plant/i.test(field))pk='eco';else if(/molecular/i.test(field))pk='molecular';else if(/physics/i.test(field))pk='physics';else if(/chem/i.test(field))pk='chemistry';const steps=layouts[type]||layouts['Graphical Abstract'];const keys=[...tokenize(topic),'arrow','label'].slice(0,9);$('#planResult').innerHTML=`<div><span class="eyebrow">RECOMMENDED VISUAL PLAN</span><h3>${esc(type)} • ${esc(field)}</h3><ol>${steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><p><strong>Suggested asset searches</strong></p><div class="tag-row">${keys.map(k=>`<span class="tag">${esc(k)}</span>`).join('')}</div><p><strong>Palette</strong></p><div class="tag-row">${palettes[pk].map(c=>`<span class="tag"><i style="display:inline-block;width:9px;height:9px;border-radius:50%;background:${c};margin-right:5px"></i>${c}</span>`).join('')}</div><p><strong>Design guidance:</strong> keep one reading direction, use short labels, preserve white space, keep line weights consistent, and use vector assets whenever available.</p></div>`};

/* ---------- AUTH ---------- */
const modal=$('#authModal');$('#openAuth').onclick=()=>modal.classList.remove('hidden');$('#closeAuth').onclick=()=>modal.classList.add('hidden');modal.onclick=e=>{if(e.target===modal)modal.classList.add('hidden')};
$$('[data-auth-tab]').forEach(b=>b.onclick=()=>{$$('[data-auth-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#loginForm').classList.toggle('hidden',b.dataset.authTab!=='login');$('#registerForm').classList.toggle('hidden',b.dataset.authTab!=='register');$('#authMessage').textContent=''});
$('#loginForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);const {error}=await sb.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});$('#authMessage').textContent=error?error.message:'Signed in successfully.';if(!error){modal.classList.add('hidden');await refreshSession()}};
$('#registerForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);$('#authMessage').textContent='Creating account…';const {data,error}=await sb.auth.signUp({email:f.get('email'),password:f.get('password')});if(error){$('#authMessage').textContent=error.message;return}if(data.user){const profile={user_id:data.user.id,full_name:f.get('full_name'),account_type:f.get('account_type'),institution:f.get('institution'),discipline:f.get('discipline'),scientific_id_type:f.get('scientific_id_type'),scientific_id_value:f.get('scientific_id_value'),scientific_id_url:f.get('scientific_id_url')||null};const {error:pe}=await sb.from('sf_profiles').insert(profile);$('#authMessage').textContent=pe?pe.message:'Registration submitted. Your account remains pending until administrator verification.'}};
$('#signOut').onclick=async()=>{await sb.auth.signOut();await refreshSession()};
async function refreshSession(){const {data:{user}}=await sb.auth.getUser();currentUser=user||null;currentProfile=null;isAdmin=false;$('#openAuth').classList.toggle('hidden',!!user);$('#signOut').classList.toggle('hidden',!user);if(!user){$('#accessStatus').textContent='Guest preview';$('#adminPanel').classList.add('hidden');$('#projectList').innerHTML='<small>Sign in to view saved projects.</small>';return}const {data:p}=await sb.from('sf_profiles').select('*').eq('user_id',user.id).maybeSingle();currentProfile=p||null;const {data:a}=await sb.from('sf_admins').select('role').eq('user_id',user.id).maybeSingle();isAdmin=!!a;const status=p?.verification_status||'profile required';$('#accessStatus').textContent=isAdmin?'Administrator':status==='approved'?'Verified user':'Pending verification';if(isAdmin){$('#adminPanel').classList.remove('hidden');await loadPending()}else $('#adminPanel').classList.add('hidden');await loadProjects()}
async function loadPending(){const {data,error}=await sb.from('sf_profiles').select('*').eq('verification_status','pending').order('created_at',{ascending:true});if(error){$('#pendingUsers').textContent=error.message;return}$('#pendingUsers').innerHTML=(data||[]).length?(data||[]).map(u=>`<div class="pending-card"><div><strong>${esc(u.full_name||'Unnamed user')}</strong><small>${esc(u.account_type)} • ${esc(u.institution||'')} • ${esc(u.discipline||'')}</small></div><div><small>${esc(u.scientific_id_type||'ID')}: ${esc(u.scientific_id_value||'')}</small>${u.scientific_id_url?`<a href="${esc(u.scientific_id_url)}" target="_blank" rel="noopener">Verification link</a>`:''}</div><div class="pending-actions"><button class="approve" data-approve="${u.user_id}">Approve</button><button class="reject" data-reject="${u.user_id}">Reject</button></div></div>`).join(''):'<p>No pending verification requests.</p>';$$('[data-approve]').forEach(b=>b.onclick=()=>setVerification(b.dataset.approve,'approved'));$$('[data-reject]').forEach(b=>b.onclick=()=>setVerification(b.dataset.reject,'rejected'))}
async function setVerification(uid,status){const {error}=await sb.rpc('sf_admin_set_verification',{target_user:uid,new_status:status,note:null});if(error)alert(error.message);await loadPending()}

/* ---------- SAVE + LOAD ---------- */
$('#saveProject').onclick=saveProject;
async function saveProject(){if(!currentUser){modal.classList.remove('hidden');$('#authMessage').textContent='Please sign in first.';return}if(!isAdmin&&currentProfile?.verification_status!=='approved'){alert('Your account must be approved by the administrator before projects can be saved.');return}selectObject(null);const payload={user_id:currentUser.id,title:$('#projectTitle').value.trim()||'Untitled scientific figure',domain:$('#studioDomain').value,canvas_width:1600,canvas_height:1000,background:'#ffffff',project_json:{svg:canvas.innerHTML,version:'0.3'}};let result;if(currentProjectId)result=await sb.from('sf_projects').update(payload).eq('id',currentProjectId).eq('user_id',currentUser.id);else result=await sb.from('sf_projects').insert(payload).select('id').single();if(result.error){alert(result.error.message);return}if(!currentProjectId&&result.data?.id)currentProjectId=result.data.id;alert('Project saved successfully.');await loadProjects()}
async function loadProjects(){if(!currentUser){$('#projectList').innerHTML='<small>Sign in to view saved projects.</small>';return}const {data,error}=await sb.from('sf_projects').select('id,title,domain,updated_at,project_json').eq('user_id',currentUser.id).order('updated_at',{ascending:false}).limit(20);if(error){$('#projectList').innerHTML=`<small>${esc(error.message)}</small>`;return}$('#projectList').innerHTML=(data||[]).length?(data||[]).map(p=>`<div class="project-row"><div><strong>${esc(p.title)}</strong><small>${esc(p.domain||'')} • ${new Date(p.updated_at).toLocaleDateString()}</small></div><button data-load-project="${p.id}">Open</button></div>`).join(''):'<small>No saved projects yet.</small>';$$('[data-load-project]').forEach(b=>b.onclick=()=>openProject(b.dataset.loadProject,data))}
function openProject(id,projects){const p=projects.find(x=>String(x.id)===String(id));if(!p)return;snapshot();canvas.innerHTML=p.project_json?.svg||'<rect width="1600" height="1000" fill="#fff" data-canvas-bg="1"/>';ensureCanvasBase();$('#projectTitle').value=p.title;$('#studioDomain').value=p.domain||'biological';renderDomain();currentProjectId=p.id;selectObject(null)}

/* ---------- EXPORT ---------- */
function cleanClone(){const clone=canvas.cloneNode(true);clone.querySelectorAll('.selection-outline').forEach(x=>x.remove());clone.querySelectorAll('.selected').forEach(x=>x.classList.remove('selected'));clone.setAttribute('xmlns',NS);clone.setAttribute('width','1600');clone.setAttribute('height','1000');return clone}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},400)}
function safeName(ext){return ($('#projectTitle').value.trim()||'scientific-figure').replace(/[^a-z0-9-_]+/gi,'-').replace(/^-|-$/g,'')+'.'+ext}
function exportSVG(){const clone=cleanClone(),xml='<?xml version="1.0" encoding="UTF-8"?>\n'+new XMLSerializer().serializeToString(clone);downloadBlob(new Blob([xml],{type:'image/svg+xml;charset=utf-8'}),safeName('svg'))}
function exportPNG(){const clone=cleanClone(),xml=new XMLSerializer().serializeToString(clone),url=URL.createObjectURL(new Blob([xml],{type:'image/svg+xml'})),img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=3200;c.height=2000;const ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);c.toBlob(blob=>blob&&downloadBlob(blob,safeName('png')),'image/png')};img.src=url}

/* ---------- ASSET REGISTRY ---------- */
$('#showRegistry').onclick=async()=>{const {data,error}=await sb.from('sf_assets').select('name,domain,style,license_name,source_name,source_url').eq('approved',true).limit(30);if(error){$('#registryResults').textContent=error.message;return}$('#registryResults').innerHTML=(data||[]).length?(data||[]).map(a=>`<div class="registry-row"><strong>${esc(a.name)}</strong><span>${esc(a.domain)}</span><span>${esc(a.style)}</span><span>${esc(a.license_name||'License recorded')}</span></div>`).join(''):'<p>No assets have been approved into the internal registry yet. External open-license sources remain available above.</p>'};

refreshSession();
