(()=>{
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const sym={cell:'◉',mitochondrion:'ϟ',dna:'⌁',virus:'✺',molecule:'⬡',flask:'⚗',atom:'⚛',wave:'∿',graph:'⌁',database:'▰',network:'◌',heatmap:'▦'};
const originalAssets=[
{name:'Cell',kind:'cell',domain:'Biology',style:'Vector'},
{name:'Mitochondrion',kind:'mitochondrion',domain:'Biology',style:'Vector'},
{name:'DNA',kind:'dna',domain:'Molecular biology',style:'Vector'},
{name:'Virus',kind:'virus',domain:'Microbiology',style:'Vector'},
{name:'Molecule',kind:'molecule',domain:'Chemistry',style:'Vector'},
{name:'Laboratory flask',kind:'flask',domain:'Chemistry',style:'Vector'},
{name:'Atom',kind:'atom',domain:'Physics',style:'Vector'},
{name:'Wave',kind:'wave',domain:'Physics',style:'Line'},
{name:'Scientific graph',kind:'graph',domain:'Mathematics',style:'Vector'},
{name:'Database',kind:'database',domain:'Bioinformatics',style:'Vector'},
{name:'Network',kind:'network',domain:'Bioinformatics',style:'Vector'},
{name:'Heatmap',kind:'heatmap',domain:'Bioinformatics',style:'Vector'}
];
let multi=new Set();

function addAssetBrowser(){
 const left=q('.left-rail'); if(!left||q('#v04AssetBrowser'))return;
 const block=document.createElement('div'); block.className='rail-block asset-browser';block.id='v04AssetBrowser';
 block.innerHTML=`<b>Scientific asset library <span class="v04-badge">v0.4</span></b><input id="v04AssetSearch" type="search" placeholder="Search starter assets"><select id="v04AssetDomain"><option value="all">All domains</option><option>Biology</option><option>Molecular biology</option><option>Microbiology</option><option>Chemistry</option><option>Physics</option><option>Mathematics</option><option>Bioinformatics</option></select><div id="v04AssetGrid" class="asset-browser-grid"></div><button id="v04RegistryOpen">Browse approved external registry</button><div class="asset-legal">Starter icons are original simple vectors generated inside SciFigure. External assets should only be inserted when their license permits reuse and adaptation.</div>`;
 left.insertBefore(block,left.children[Math.min(2,left.children.length)]||null);
 const render=()=>{const term=q('#v04AssetSearch').value.toLowerCase(),dom=q('#v04AssetDomain').value;const rows=originalAssets.filter(a=>(dom==='all'||a.domain===dom)&&(!term||(`${a.name} ${a.domain} ${a.style}`).toLowerCase().includes(term)));q('#v04AssetGrid').innerHTML=rows.map(a=>`<button class="asset-card" data-v04asset="${a.kind}"><span class="asset-thumb">${sym[a.kind]||'◻'}</span><strong>${a.name}</strong><small>${a.domain} • ${a.style}</small></button>`).join('');qa('[data-v04asset]').forEach(b=>b.onclick=()=>addStarter(b.dataset.v04asset));};
 q('#v04AssetSearch').oninput=render;q('#v04AssetDomain').onchange=render;render();q('#v04RegistryOpen').onclick=openRegistryModal;
}

function addAdvancedTools(){
 const right=q('.right-rail');if(!right||q('#v04Advanced'))return;
 const block=document.createElement('div');block.className='rail-block v04-panel';block.id='v04Advanced';
 block.innerHTML=`<b>Advanced edit <span class="v04-badge">v0.4</span></b><label>Rotation (°)<input id="v04Rotate" type="range" min="-180" max="180" value="0"></label><div class="v04-grid"><button data-align="left">Left</button><button data-align="center">Center</button><button data-align="right">Right</button><button data-align="top">Top</button><button data-align="middle">Middle</button><button data-align="bottom">Bottom</button></div><div class="v04-divider"></div><label>Text / label content<input id="v04Text" type="text" placeholder="Select a text object"></label><div class="v04-inline"><label>Font size<input id="v04FontSize" type="number" min="8" max="180" value="42"></label><label>Weight<select id="v04FontWeight"><option value="400">Regular</option><option value="600" selected>Semi-bold</option><option value="700">Bold</option></select></label></div><div class="v04-grid two"><button id="v04Italic">Italic</button><button id="v04ApplyText">Apply text</button></div><div class="v04-divider"></div><div class="v04-grid two"><button id="v04Group">Group selected</button><button id="v04Ungroup">Ungroup</button></div><div class="v04-toolbar-note">Shift-click objects to build a multi-selection, then group them.</div><div class="v04-divider"></div><label>Connector style<select id="v04LineStyle"><option value="solid">Solid</option><option value="dash">Dashed</option><option value="dot">Dotted</option></select></label><button id="v04ApplyLine">Apply to selected line/arrow</button>`;
 right.prepend(block);
 q('#v04Rotate').oninput=e=>rotateSelected(+e.target.value);qa('[data-align]').forEach(b=>b.onclick=()=>alignSelection(b.dataset.align));q('#v04ApplyText').onclick=applyText;q('#v04Italic').onclick=toggleItalic;q('#v04Group').onclick=groupSelection;q('#v04Ungroup').onclick=ungroupSelected;q('#v04ApplyLine').onclick=applyLineStyle;
}

function selectedSet(){return multi.size?[...multi]:(selected?[selected]:[])}
function rotateSelected(deg){selectedSet().forEach(g=>{g.dataset.rotate=deg;applyTransformV04(g)})}
function applyTransformV04(g){const x=+(g.dataset.x||0),y=+(g.dataset.y||0),s=+(g.dataset.scale||1),r=+(g.dataset.rotate||0);g.setAttribute('transform',`translate(${x} ${y}) rotate(${r}) scale(${s})`)}
function alignSelection(mode){const els=selectedSet();if(!els.length)return;snapshot();els.forEach(g=>{let b;try{b=g.getBBox()}catch{return}const s=+(g.dataset.scale||1);let x=+(g.dataset.x||0),y=+(g.dataset.y||0);const w=b.width*s,h=b.height*s;if(mode==='left')x=40-b.x*s;if(mode==='center')x=800-(b.x*s+w/2);if(mode==='right')x=1560-(b.x*s+w);if(mode==='top')y=40-b.y*s;if(mode==='middle')y=500-(b.y*s+h/2);if(mode==='bottom')y=960-(b.y*s+h);g.dataset.x=x;g.dataset.y=y;applyTransformV04(g)})}
function applyText(){if(!selected)return;const t=selected.querySelector('text');if(!t)return; snapshot();t.textContent=q('#v04Text').value||t.textContent;t.setAttribute('font-size',q('#v04FontSize').value||42);t.setAttribute('font-weight',q('#v04FontWeight').value||600)}
function toggleItalic(){if(!selected)return;const t=selected.querySelector('text');if(!t)return;snapshot();t.setAttribute('font-style',t.getAttribute('font-style')==='italic'?'normal':'italic')}
function groupSelection(){const els=selectedSet();if(els.length<2)return;snapshot();const group=svgEl('g',{'class':'sf-object','data-kind':'group','data-x':'0','data-y':'0','data-scale':'1','data-rotate':'0'});els.forEach(el=>{el.classList.remove('sf-object','selected','multi-selected');const o=el.querySelector(':scope > .selection-outline');if(o)o.remove();group.appendChild(el)});canvas.appendChild(group);let bb;try{bb=group.getBBox();group.appendChild(outline(bb.x-8,bb.y-8,bb.width+16,bb.height+16))}catch{}multi.clear();selectObject(group)}
function ungroupSelected(){if(!selected||selected.dataset.kind!=='group')return;snapshot();const g=selected;const children=[...g.children].filter(c=>!c.classList.contains('selection-outline'));children.forEach(c=>{c.classList.add('sf-object');canvas.appendChild(c)});g.remove();selectObject(null)}
function applyLineStyle(){if(!selected)return;const style=q('#v04LineStyle').value;const lines=selected.querySelectorAll('line,path');snapshot();lines.forEach(el=>{if(style==='solid')el.removeAttribute('stroke-dasharray');if(style==='dash')el.setAttribute('stroke-dasharray','18 10');if(style==='dot')el.setAttribute('stroke-dasharray','3 12')})}

function bindMultiSelect(){canvas.addEventListener('pointerdown',e=>{const g=e.target.closest?.('.sf-object');if(!e.shiftKey||!g)return;e.preventDefault();if(multi.has(g)){multi.delete(g);g.classList.remove('multi-selected')}else{multi.add(g);g.classList.add('multi-selected')}q('#selectedNote').textContent=multi.size?`${multi.size} objects selected`:'Select an object on the canvas.'},true);canvas.addEventListener('click',e=>{const g=e.target.closest?.('.sf-object');if(g&&!e.shiftKey){multi.forEach(x=>x.classList.remove('multi-selected'));multi.clear();const t=g.querySelector('text');if(t){q('#v04Text').value=t.textContent||'';q('#v04FontSize').value=parseInt(t.getAttribute('font-size')||42);q('#v04FontWeight').value=t.getAttribute('font-weight')||600}q('#v04Rotate').value=+(g.dataset.rotate||0)}})}

function openRegistryModal(){let m=q('#v04RegistryModal');if(!m){m=document.createElement('div');m.id='v04RegistryModal';m.className='v04-modal';m.innerHTML=`<div class="v04-modal-card"><div class="v04-modal-head"><div><span class="eyebrow">APPROVED ASSET REGISTRY</span><h2>License-aware external scientific assets</h2></div><button id="v04CloseRegistry">×</button></div><div class="v04-inline"><input id="v04RegistrySearch" type="search" placeholder="Search registry"><select id="v04RegistryStyle"><option value="all">All styles</option><option value="Vector">Vector</option><option value="Sketch">Sketch</option><option value="Color">Color</option><option value="3D">3D</option></select></div><p class="asset-legal">Only records marked approved by the platform are shown. Always preserve source and attribution requirements in final publication materials.</p><div id="v04RegistryResults" class="registry-browser"></div></div>`;document.body.appendChild(m);q('#v04CloseRegistry').onclick=()=>m.classList.add('hidden');m.onclick=e=>{if(e.target===m)m.classList.add('hidden')};q('#v04RegistrySearch').oninput=loadRegistry;q('#v04RegistryStyle').onchange=loadRegistry}else m.classList.remove('hidden');loadRegistry()}
async function loadRegistry(){const box=q('#v04RegistryResults');if(!box)return;box.innerHTML='<p>Loading approved assets…</p>';let req=sb.from('sf_assets').select('id,name,domain,kind,style,source_name,source_url,preview_url,download_url,license_name,license_url,attribution_required,attribution_text,editable_svg,keywords').eq('approved',true).limit(60);const term=(q('#v04RegistrySearch')?.value||'').trim();const style=q('#v04RegistryStyle')?.value||'all';if(term)req=req.ilike('name',`%${term}%`);if(style!=='all')req=req.eq('style',style);const {data,error}=await req;if(error){box.innerHTML=`<p>${error.message}</p>`;return}box.innerHTML=(data||[]).length?(data||[]).map(a=>`<article class="registry-asset">${a.preview_url?`<img src="${a.preview_url}" alt="${escapeHtml(a.name)}" loading="lazy">`:'<div class="asset-thumb">◻</div>'}<strong>${escapeHtml(a.name)}</strong><small>${escapeHtml(a.domain||'Scientific')} • ${escapeHtml(a.style||a.kind||'Asset')}</small><small>${escapeHtml(a.source_name||'Source')} • ${escapeHtml(a.license_name||'License recorded')}</small><div class="registry-actions">${a.source_url?`<a href="${a.source_url}" target="_blank" rel="noopener">Source</a>`:''}${a.download_url?`<a href="${a.download_url}" target="_blank" rel="noopener">Asset</a>`:''}<button data-attrib="${a.id}">Attribution</button></div></article>`).join(''):'<p>No external assets have been approved yet. The internal starter vector library remains available.</p>';qa('[data-attrib]').forEach(b=>b.onclick=()=>showAttribution(data.find(a=>String(a.id)===b.dataset.attrib)))}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function showAttribution(a){if(!a)return;alert(`${a.name}\nSource: ${a.source_name||''}\nLicense: ${a.license_name||''}\nAttribution required: ${a.attribution_required?'Yes':'No'}\n${a.attribution_text||''}`)}

function addAttributionTools(){const right=q('.right-rail');if(!right||q('#v04Attribution'))return;const b=document.createElement('div');b.className='rail-block v04-panel';b.id='v04Attribution';b.innerHTML=`<b>Publication check</b><button id="v04Audit">Audit current figure</button><button id="v04AttributionReport">Generate attribution note</button><div id="v04Report" class="v04-report">No audit run yet.</div>`;right.appendChild(b);q('#v04Audit').onclick=auditFigure;q('#v04AttributionReport').onclick=attributionReport}
function auditFigure(){const objs=canvas.querySelectorAll('.sf-object').length,texts=canvas.querySelectorAll('.sf-object text').length,lines=canvas.querySelectorAll('.sf-object line,.sf-object path').length;const warnings=[];if(objs>18)warnings.push('High object count: consider simplifying the visual story.');if(texts>10)warnings.push('Many text labels: shorten labels where possible.');if(lines>30)warnings.push('Many connectors/paths: check visual clutter.');const white=canvas.querySelector('rect[width="1600"][height="1000"]');if(!white)warnings.push('Canvas background may no longer be the standard white publication background.');q('#v04Report').textContent=`Objects: ${objs}\nText labels: ${texts}\nLines/paths: ${lines}\n${warnings.length?'\nChecks:\n- '+warnings.join('\n- '):'\nNo obvious layout warnings from the basic audit.'}`}
function attributionReport(){q('#v04Report').textContent='SciFigure Commons original starter vectors: no external attribution recorded.\n\nFor any externally sourced icon or illustration, retain its source, license, creator/attribution text, and indicate modifications when required by the license. The approved external registry will generate per-asset attribution as records are added.'}

function patchObjectTransform(){const obs=new MutationObserver(()=>{canvas.querySelectorAll('.sf-object').forEach(g=>{if(g.dataset.rotate===undefined)g.dataset.rotate='0'})});obs.observe(canvas,{childList:true,subtree:true})}

addAssetBrowser();addAdvancedTools();addAttributionTools();bindMultiSelect();patchObjectTransform();
})();