(()=>{
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
if(!window.supabase||!q('#figureCanvas')) return;
const canvas=q('#figureCanvas');
const NS='http://www.w3.org/2000/svg';

function svgEl(tag,attrs={}){const e=document.createElementNS(NS,tag);Object.entries(attrs).forEach(([k,v])=>e.setAttribute(k,v));return e}
function ensureBg(fill='#ffffff'){let bg=canvas.querySelector(':scope > rect:not(.selection-outline)');if(!bg){bg=svgEl('rect',{width:'100%',height:'100%',fill});canvas.insertBefore(bg,canvas.firstChild)}bg.setAttribute('fill',fill);return bg}
function clearObjects(){snapshot();qa('#figureCanvas .sf-object').forEach(x=>x.remove())}
function safeText(s){return String(s||'').replace(/[<>]/g,'')}
function shortWords(text,max=6){return [...new Set(String(text||'').toLowerCase().replace(/[^a-z0-9α-ωΑ-Ω\s-]/g,' ').split(/\s+/).filter(x=>x.length>3))].slice(0,max)}
function addLabel(text,x,y,size=34,color){const g=makeObject('text',x,y);const t=svgEl('text',{x:0,y:0,fill:color||q('#elementColor').value,'font-size':size,'font-family':'Arial, sans-serif','font-weight':600,'data-colorable':'fill'});t.textContent=text;g.append(t,outline(-10,-48,Math.max(180,text.length*21),70));canvas.appendChild(g);return g}
function addArrowBetween(x1,y1,x2,y2){ensureArrowMarker();const g=makeObject('arrow',x1,y1);const line=svgEl('line',{x1:0,y1:0,x2:x2-x1,y2:y2-y1,stroke:q('#elementColor').value,'stroke-width':5,'stroke-linecap':'round','marker-end':'url(#sfArrow)','data-colorable':'stroke'});g.append(line,outline(-8,Math.min(0,y2-y1)-18,Math.abs(x2-x1)+26,Math.abs(y2-y1)+36));canvas.appendChild(g);return g}
function placeStarter(kind,x,y,scale=.8){const before=canvas.querySelectorAll('.sf-object').length;addStarter(kind);const objects=qa('#figureCanvas .sf-object');const g=objects[objects.length-1];if(objects.length>before&&g){g.dataset.x=x;g.dataset.y=y;g.dataset.scale=scale;if(typeof updateTransform==='function')updateTransform(g)}return g}

function addV05Panels(){const left=q('.left-rail'),right=q('.right-rail');if(!left||!right||q('#v05Assistant'))return;
 const assist=document.createElement('div');assist.id='v05Assistant';assist.className='rail-block v05-panel';assist.innerHTML=`<b>Assisted figure builder <span class="v05-badge">v0.5</span></b><textarea id="v05Concept" rows="4" placeholder="Describe mechanism, workflow, model or study"></textarea><label>Draft type<select id="v05DraftType"><option value="mechanism">Mechanism</option><option value="workflow">Experimental workflow</option><option value="bioinformatics">Bioinformatics pipeline</option><option value="chemistry">Chemical scheme</option><option value="math">Mathematical model</option></select></label><button id="v05BuildDraft">Build editable draft</button><div class="v05-ai-banner"><b>Cost-free MVP:</b><span>Creates a structured editable draft locally. A secure model backend can later replace the rule-based planner.</span></div>`;left.insertBefore(assist,left.firstChild?.nextSibling||null);
 const templates=document.createElement('div');templates.className='rail-block v05-panel';templates.innerHTML=`<b>Domain templates</b><div class="v05-template-grid"><button data-v05tpl="cell-mechanism">Cell mechanism<small>3-step pathway</small></button><button data-v05tpl="drug-workflow">Drug workflow<small>screen → validate</small></button><button data-v05tpl="ml-pipeline">ML pipeline<small>data → model → test</small></button><button data-v05tpl="chemical-reaction">Reaction scheme<small>reactant → product</small></button><button data-v05tpl="equation-model">Equation model<small>variables → model</small></button><button data-v05tpl="clinical-flow">Clinical flow<small>cohort → outcome</small></button></div>`;left.appendChild(templates);
 const publish=document.createElement('div');publish.className='rail-block v05-panel';publish.innerHTML=`<b>Publication setup</b><button id="v05Presets">Canvas / journal presets</button><div class="v05-export-row"><button id="v05Transparent">Transparent PNG</button><button id="v05CopySvg">Copy SVG</button></div><button id="v05ImportSvg">Import approved SVG URL</button><div class="v05-note">Only import an external SVG when its license clearly permits reuse. Keep attribution where required.</div>`;right.appendChild(publish);
 q('#v05BuildDraft').onclick=buildDraft;qa('[data-v05tpl]').forEach(b=>b.onclick=()=>applyTemplate(b.dataset.v05tpl));q('#v05Presets').onclick=openPresetModal;q('#v05Transparent').onclick=exportTransparent;q('#v05CopySvg').onclick=copySvg;q('#v05ImportSvg').onclick=openImportModal;
}

function titleAndSteps(text,type){const words=shortWords(text,8);let steps=[];if(type==='mechanism')steps=[words[0]||'Trigger',words[1]||'Mechanism',words[2]||'Response',words[3]||'Outcome'];
 if(type==='workflow')steps=['Sample / input','Preparation','Assay / analysis','Validation'];
 if(type==='bioinformatics')steps=['Raw data','Preprocessing','Feature / model','Validation','Interpretation'];
 if(type==='chemistry')steps=[words[0]||'Reactant','Reaction / catalyst',words[1]||'Intermediate',words[2]||'Product'];
 if(type==='math')steps=['Variables','Assumptions','Equation / model','Simulation','Outcome'];return {title:safeText(text).slice(0,90)||'Scientific figure',steps};}
function buildDraft(){const text=q('#v05Concept').value.trim()||q('#topic')?.value.trim()||'';if(!text){q('#v05Concept').focus();return}const type=q('#v05DraftType').value;const {title,steps}=titleAndSteps(text,type);snapshot();clearObjects();ensureBg('#ffffff');q('#projectTitle').value=title;addLabel(title,100,90,38,'#172033');const n=steps.length,start=130,gap=(1340)/(Math.max(1,n-1));steps.forEach((s,i)=>{const x=start+i*gap,y=410;const domainKind=type==='bioinformatics'?(i===0?'database':i===2?'network':i===3?'graph':'heatmap'):type==='chemistry'?(i===0?'molecule':i===1?'flask':i===3?'molecule':'atom'):type==='math'?(i===0?'graph':i===2?'graph':'database'):type==='mechanism'?(i===0?'cell':i===1?'mitochondrion':i===2?'molecule':'cell'):(i===0?'flask':i===2?'graph':'molecule');placeStarter(domainKind,x-100,y-100,.65);addLabel(s,x-95,590,26,'#23324a');if(i<n-1)addArrowBetween(x+80,y,x+gap-80,y)});selectObject(null)}
function applyTemplate(name){const map={
 'cell-mechanism':{type:'mechanism',text:'Cellular trigger activates intracellular mechanism leading to biological response'},
 'drug-workflow':{type:'workflow',text:'Compound screening followed by target validation and functional testing'},
 'ml-pipeline':{type:'bioinformatics',text:'Dataset preprocessing feature engineering machine learning validation interpretation'},
 'chemical-reaction':{type:'chemistry',text:'Reactant catalyst intermediate product'},
 'equation-model':{type:'math',text:'Variables assumptions mathematical model simulation predicted outcome'},
 'clinical-flow':{type:'workflow',text:'Patient cohort assessment intervention outcome validation'}};const x=map[name];q('#v05Concept').value=x.text;q('#v05DraftType').value=x.type;buildDraft()}

function setCanvasPreset(w,h,label){snapshot();canvas.setAttribute('viewBox',`0 0 ${w} ${h}`);canvas.dataset.canvasWidth=w;canvas.dataset.canvasHeight=h;ensureBg('#ffffff').setAttribute('width',w);ensureBg('#ffffff').setAttribute('height',h);const note=q('.canvas-note');if(note)note.textContent=`${label}: ${w} × ${h} • vector-first workflow`;closePresetModal()}
function openPresetModal(){if(q('#v05PresetModal')){q('#v05PresetModal').classList.remove('hidden');return}const m=document.createElement('div');m.id='v05PresetModal';m.className='v05-modal';m.innerHTML=`<div class="v05-card"><div class="v05-card-head"><div><span class="eyebrow">PUBLICATION PRESETS</span><h2>Canvas size</h2></div><button data-close>×</button></div><div class="v05-preset-list"><button data-preset="1600,1000,Graphical abstract"><strong>Graphical abstract</strong><span>1600 × 1000</span></button><button data-preset="1800,1200,Journal landscape"><strong>Journal landscape</strong><span>1800 × 1200</span></button><button data-preset="1200,1800,Journal portrait"><strong>Journal portrait</strong><span>1200 × 1800</span></button><button data-preset="1920,1080,Presentation 16:9"><strong>Presentation 16:9</strong><span>1920 × 1080</span></button><button data-preset="2480,3508,A4 portrait 300 dpi"><strong>A4 portrait</strong><span>2480 × 3508</span></button></div></div>`;document.body.appendChild(m);m.querySelector('[data-close]').onclick=closePresetModal;m.onclick=e=>{if(e.target===m)closePresetModal()};m.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const [w,h,l]=b.dataset.preset.split(',');setCanvasPreset(+w,+h,l)})}
function closePresetModal(){q('#v05PresetModal')?.classList.add('hidden')}

async function copySvg(){selectObject(null);const clone=canvas.cloneNode(true);clone.querySelectorAll('.selection-outline').forEach(x=>x.remove());const xml=new XMLSerializer().serializeToString(clone);try{await navigator.clipboard.writeText(xml);alert('SVG markup copied to clipboard.')}catch{alert('Clipboard access is unavailable in this browser. Use SVG export instead.')}}
function exportTransparent(){selectObject(null);const clone=canvas.cloneNode(true);clone.querySelectorAll('.selection-outline').forEach(x=>x.remove());const bg=clone.querySelector(':scope > rect:not(.selection-outline)');if(bg)bg.setAttribute('fill','none');const vb=clone.viewBox.baseVal;const w=vb.width||1600,h=vb.height||1000;clone.setAttribute('width',w*2);clone.setAttribute('height',h*2);const xml=new XMLSerializer().serializeToString(clone),blob=new Blob([xml],{type:'image/svg+xml'}),url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=w*2;c.height=h*2;c.getContext('2d').drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);c.toBlob(b=>{const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=(q('#projectTitle').value||'scifigure').replace(/[^a-z0-9-_]+/gi,'_')+'_transparent.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)},'image/png')};img.src=url}

function openImportModal(){let m=q('#v05ImportModal');if(!m){m=document.createElement('div');m.id='v05ImportModal';m.className='v05-modal';m.innerHTML=`<div class="v05-card"><div class="v05-card-head"><div><span class="eyebrow">LICENSE-AWARE IMPORT</span><h2>Import approved SVG</h2></div><button data-close>×</button></div><label>SVG file URL<input id="v05SvgUrl" type="url" placeholder="https://.../asset.svg"></label><label>Source / creator<input id="v05SvgSource" type="text" placeholder="Creator or library"></label><label>License<input id="v05SvgLicense" type="text" placeholder="e.g. CC0, CC BY 4.0, MIT"></label><label>Attribution text<input id="v05SvgAttr" type="text" placeholder="Required attribution, if any"></label><button class="btn primary full" id="v05DoImport">Fetch and insert SVG</button><p id="v05ImportStatus" class="v05-status"></p><div class="v05-import-preview">The browser will only import a remote SVG if the source permits cross-origin access. If blocked, download the legally reusable SVG and add it to the project repository instead.</div></div>`;document.body.appendChild(m);m.querySelector('[data-close]').onclick=()=>m.classList.add('hidden');m.onclick=e=>{if(e.target===m)m.classList.add('hidden')};q('#v05DoImport').onclick=importRemoteSvg}else m.classList.remove('hidden')}
async function importRemoteSvg(){const url=q('#v05SvgUrl').value.trim(),source=q('#v05SvgSource').value.trim(),license=q('#v05SvgLicense').value.trim(),attr=q('#v05SvgAttr').value.trim(),status=q('#v05ImportStatus');if(!url||!license){status.textContent='Please provide the SVG URL and its license.';return}status.textContent='Fetching SVG…';try{const r=await fetch(url,{mode:'cors'});if(!r.ok)throw new Error('HTTP '+r.status);const txt=await r.text();if(!/<svg[\s>]/i.test(txt))throw new Error('The URL did not return SVG content.');const doc=new DOMParser().parseFromString(txt,'image/svg+xml'),src=doc.documentElement;if(src.nodeName.toLowerCase()!=='svg')throw new Error('Invalid SVG.');src.querySelectorAll('script,foreignObject').forEach(x=>x.remove());src.querySelectorAll('*').forEach(el=>{[...el.attributes].forEach(a=>{if(/^on/i.test(a.name)||/javascript:/i.test(a.value))el.removeAttribute(a.name)})});const g=makeObject('external-svg',220,180);g.dataset.source=source;g.dataset.license=license;g.dataset.attribution=attr;const inner=svgEl('g');[...src.childNodes].forEach(n=>inner.appendChild(document.importNode(n,true)));g.appendChild(inner);g.appendChild(outline(-10,-10,420,320));addToCanvas(g);status.textContent='Imported. Preserve the recorded license and attribution when publishing.'}catch(e){status.textContent='Import blocked or failed: '+e.message}}

function addEquationTools(){const left=q('.left-rail');if(!left||q('#v05MathChem'))return;const b=document.createElement('div');b.id='v05MathChem';b.className='rail-block v05-panel';b.innerHTML=`<b>Chemistry & mathematics</b><div class="v05-grid"><button data-special="benzene">Benzene ring</button><button data-special="equation">Equation</button><button data-special="axis">X–Y axes</button><button data-special="matrix">Matrix</button></div>`;left.appendChild(b);qa('[data-special]').forEach(x=>x.onclick=()=>insertSpecial(x.dataset.special))}
function insertSpecial(kind){snapshot();const p={x:260,y:250};const g=makeObject(kind,p.x,p.y),c=q('#elementColor').value,a=q('#accentColor').value;if(kind==='benzene'){let pts=[];for(let i=0;i<6;i++){const ang=-Math.PI/2+i*Math.PI/3;pts.push(`${100+80*Math.cos(ang)},${100+80*Math.sin(ang)}`)}g.append(svgEl('polygon',{points:pts.join(' '),fill:'none',stroke:c,'stroke-width':6,'data-colorable':'stroke'}),svgEl('circle',{cx:100,cy:100,r:46,fill:'none',stroke:a,'stroke-width':5,'data-accentable':'stroke'}),outline(0,0,205,205))}else if(kind==='equation'){const t=svgEl('text',{x:0,y:50,fill:c,'font-size':46,'font-family':'Cambria Math, Times New Roman, serif','data-colorable':'fill'});t.textContent='y = β₀ + β₁x + ε';g.append(t,outline(-10,0,390,80))}else if(kind==='axis'){g.append(svgEl('line',{x1:20,y1:220,x2:20,y2:10,stroke:c,'stroke-width':5}),svgEl('line',{x1:20,y1:220,x2:300,y2:220,stroke:c,'stroke-width':5}),outline(0,0,320,240))}else{const t=svgEl('text',{x:0,y:55,fill:c,'font-size':44,'font-family':'Cambria Math, serif','data-colorable':'fill'});t.textContent='[ a  b ; c  d ]';g.append(t,outline(-10,0,330,85))}addToCanvas(g)}

addV05Panels();addEquationTools();ensureBg('#ffffff');
})();