(()=>{
'use strict';
const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
const canvas=q('#figureCanvas');
if(!canvas) return;
const APP_VERSION='0.6.0';
const SAFE_PROTOCOL=/^https?:$/i;
const nativeAlert=window.alert.bind(window);

/* ---------- Core reliability patches ---------- */
function dims(){const vb=canvas.viewBox?.baseVal;return {w:Math.round(vb?.width||+(canvas.dataset.canvasWidth||1600)),h:Math.round(vb?.height||+(canvas.dataset.canvasHeight||1000))}}
function transformOf(g){const x=+(g.dataset.x||0),y=+(g.dataset.y||0),s=+(g.dataset.scale||1),r=+(g.dataset.rotate||0);return `translate(${x} ${y}) rotate(${r}) scale(${s})`}
try{updateTransform=function(g){if(g)g.setAttribute('transform',transformOf(g))}}catch{}

function safeUrl(raw){try{const u=new URL(raw,location.href);return SAFE_PROTOCOL.test(u.protocol)?u.href:''}catch{return ''}}
function sanitizeDynamicUrls(root=document){root.querySelectorAll?.('a[href],img[src]').forEach(el=>{const attr=el.tagName==='A'?'href':'src',raw=el.getAttribute(attr)||'',safe=safeUrl(raw);if(!safe)el.removeAttribute(attr);else el.setAttribute(attr,safe);if(el.tagName==='A'){el.setAttribute('rel','noopener noreferrer');if(el.target==='_blank')el.referrerPolicy='no-referrer'}})}
const urlObserver=new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1)sanitizeDynamicUrls(n)})));urlObserver.observe(document.body,{childList:true,subtree:true});sanitizeDynamicUrls();

/* ---------- Unified professional shell ---------- */
document.body.classList.add('sf-pro');
qa('.v04-badge,.v05-badge').forEach(x=>x.remove());
const studio=q('#studio .section-head');
if(studio && !q('#sfProHeader')){
 const bar=document.createElement('div');bar.id='sfProHeader';bar.className='sf-probar';
 bar.innerHTML=`<div class="sf-probar-left"><span class="sf-product-dot">SF</span><div><strong>SciFigure Studio</strong><small>Publication Workspace • CITics Bio Solutions × GDR Network</small></div></div><div class="sf-probar-actions"><button data-pro="new" title="New figure">＋ <span>New</span></button><button data-pro="smart" title="Scientific Copilot">✦ <span>Copilot</span></button><button data-pro="audit" title="Figure quality audit">✓ <span>Audit</span></button><button data-pro="arrange" title="Auto-arrange">⇆ <span>Arrange</span></button><button data-pro="test" title="System diagnostics">⚙ <span>Test</span></button></div>`;
 studio.parentNode.insertBefore(bar,studio.nextSibling);
}

function addCopilot(){const left=q('.left-rail');if(!left||q('#sfCopilot'))return;const panel=document.createElement('div');panel.id='sfCopilot';panel.className='rail-block sf-copilot';panel.innerHTML=`<div class="sf-panel-title"><span class="sf-ai-icon">✦</span><div><b>Scientific Copilot</b><small>Structure • assets • quality</small></div></div><textarea id="sfCopilotPrompt" rows="4" placeholder="Describe your mechanism, experiment, pathway, model or graphical abstract…"></textarea><label>Scientific mode<select id="sfCopilotMode"><option value="auto">Auto-detect</option><option value="mechanism">Biological mechanism</option><option value="workflow">Experimental workflow</option><option value="bioinformatics">Bioinformatics / ML</option><option value="chemistry">Chemistry</option><option value="math">Mathematics</option><option value="clinical">Clinical pathway</option></select></label><div class="sf-copilot-actions"><button id="sfAnalyze">Analyze</button><button id="sfBuild" class="primary-mini">Build draft</button></div><div id="sfCopilotOutput" class="sf-ai-output"><span>Copilot never validates scientific truth automatically. Verify mechanisms, labels and claims before publication.</span></div>`;left.insertBefore(panel,left.firstChild?.nextSibling||null);q('#sfAnalyze').onclick=analyzeConcept;q('#sfBuild').onclick=buildFromCopilot}
addCopilot();

const assetMap=[
 {re:/mitochond|respirat|atp/i,asset:'Mitochondrion'}, {re:/dna|gene|genom|mutation|pcr/i,asset:'DNA'}, {re:/virus|viral/i,asset:'Virus'},
 {re:/bacter|microbi|microbe/i,asset:'Bacterium / Cell'}, {re:/cell|tumou?r|neuron|immune/i,asset:'Cell'}, {re:/protein|enzyme|receptor|kinase/i,asset:'Protein / Molecule'},
 {re:/drug|compound|molecul|ligand|chem/i,asset:'Molecule'}, {re:/assay|experiment|culture|reaction/i,asset:'Laboratory flask'}, {re:/database|dataset|omics|rna-seq|sequenc/i,asset:'Database'},
 {re:/network|ppi|pathway/i,asset:'Network'}, {re:/heatmap|expression/i,asset:'Heatmap'}, {re:/model|machine learning|classifier|prediction/i,asset:'Graph / Network'},
 {re:/wave|signal|frequency|spectr/i,asset:'Wave'}, {re:/atom|quantum|electron/i,asset:'Atom'}, {re:/equation|regression|probab|statistic/i,asset:'Equation / Graph'}
];
function detectMode(text){const chosen=q('#sfCopilotMode')?.value;if(chosen&&chosen!=='auto')return chosen;if(/machine learning|bioinform|omics|rna-seq|genom|dataset|classifier/i.test(text))return 'bioinformatics';if(/reaction|catalyst|compound|synthesis|molecule/i.test(text))return 'chemistry';if(/equation|mathemat|model|probability|regression/i.test(text))return 'math';if(/patient|clinical|cohort|treatment|outcome/i.test(text))return 'clinical';if(/sample|assay|protocol|experiment|incubat|measure/i.test(text))return 'workflow';return 'mechanism'}
function conceptParts(text){return text.split(/(?:\.|;|→|->|\bthen\b|\bleads? to\b|\bcauses?\b|\bresults? in\b|\bthrough\b|\bvia\b)/i).map(s=>s.trim()).filter(Boolean).slice(0,5)}
function recommendedAssets(text){const out=[];assetMap.forEach(x=>{if(x.re.test(text)&&!out.includes(x.asset))out.push(x.asset)});return out.slice(0,6)}
function analyzeConcept(){const text=(q('#sfCopilotPrompt')?.value||'').trim();const out=q('#sfCopilotOutput');if(!text){q('#sfCopilotPrompt')?.focus();return}const mode=detectMode(text),parts=conceptParts(text),assets=recommendedAssets(text);const warnings=[];if(text.length<35)warnings.push('Add a little more scientific context for a stronger draft.');if(parts.length<2)warnings.push('The concept has few explicit stages; the draft will use a generic scientific flow.');out.innerHTML=`<strong>${labelMode(mode)}</strong><ol>${(parts.length?parts:['Input / context','Mechanism / analysis','Outcome']).map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ol><b>Suggested visual assets</b><div class="sf-chiprow">${(assets.length?assets:['Scientific label','Arrow','Result panel']).map(x=>`<span>${escapeHtml(x)}</span>`).join('')}</div>${warnings.length?`<div class="sf-ai-warning">${warnings.map(escapeHtml).join(' ')}</div>`:''}<small>AI-style guidance is structural only; verify all scientific claims.</small>`}
function labelMode(m){return ({mechanism:'Biological mechanism',workflow:'Experimental workflow',bioinformatics:'Bioinformatics / ML pipeline',chemistry:'Chemical scheme',math:'Mathematical model',clinical:'Clinical pathway'})[m]||'Scientific figure'}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function buildFromCopilot(){const text=(q('#sfCopilotPrompt')?.value||'').trim();if(!text){q('#sfCopilotPrompt')?.focus();return}const mode=detectMode(text);const target=q('#v05Concept'),type=q('#v05DraftType'),btn=q('#v05BuildDraft');if(target&&type&&btn){target.value=text;type.value=mode==='clinical'?'workflow':mode;btn.click();q('#studio')?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>runQualityAudit(true),120)}else nativeAlert('Draft builder is unavailable. Reload the page and try again.')}

/* ---------- Smart layout + keyboard workflow ---------- */
function objects(){return qa('#figureCanvas .sf-object')}
function autoArrange(){const os=objects();if(!os.length)return;try{snapshot()}catch{};const {w,h}=dims(),margin=90,cols=Math.min(5,Math.max(1,Math.ceil(Math.sqrt(os.length*w/h)))),rows=Math.ceil(os.length/cols),cw=(w-margin*2)/cols,ch=(h-margin*2)/rows;os.forEach((g,i)=>{const col=i%cols,row=Math.floor(i/cols);g.dataset.x=Math.round(margin+col*cw+cw*.12);g.dataset.y=Math.round(margin+row*ch+ch*.16);g.dataset.scale=Math.min(1,Math.max(.55,+g.dataset.scale||1));updateTransform(g)});try{selectObject(null)}catch{};toast('Objects arranged on a balanced grid.')}
function newFigure(){if(objects().length&&!confirm('Start a new figure? Unsaved canvas changes will be cleared.'))return;try{snapshot()}catch{};const {w,h}=dims();canvas.innerHTML=`<rect width="${w}" height="${h}" fill="#ffffff" data-canvas-bg="1"/>`;try{currentProjectId=null;selectObject(null)}catch{};q('#projectTitle').value='Untitled scientific figure';toast('New figure created.')}

function shortcuts(e){if(/INPUT|TEXTAREA|SELECT/.test(document.activeElement?.tagName))return;const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();q('#saveProject')?.click()}else if(mod&&e.key.toLowerCase()==='z'){e.preventDefault();q('#undoBtn')?.click()}else if(mod&&e.key.toLowerCase()==='d'){e.preventDefault();try{duplicateSelected()}catch{}}else if(e.key==='Delete'||e.key==='Backspace'){try{deleteSelected()}catch{}}else if(selected&&['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const step=e.shiftKey?10:2;selected.dataset.x=+(selected.dataset.x||0)+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0);selected.dataset.y=+(selected.dataset.y||0)+(e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0);updateTransform(selected)}}
document.addEventListener('keydown',shortcuts);

/* ---------- Dynamic canvas-aware save/load/export ---------- */
async function saveProjectV06(){if(!currentUser){q('#authModal')?.classList.remove('hidden');q('#authMessage').textContent='Please sign in first.';return}if(!isAdmin&&currentProfile?.verification_status!=='approved'){toast('Administrator approval is required before cloud saving.','warn');return}try{selectObject(null)}catch{};const {w,h}=dims();const payload={user_id:currentUser.id,title:q('#projectTitle').value.trim()||'Untitled scientific figure',domain:q('#studioDomain').value,canvas_width:w,canvas_height:h,background:'#ffffff',project_json:{svg:canvas.innerHTML,version:APP_VERSION,canvas:{width:w,height:h},updated_at:new Date().toISOString()}};let result;if(currentProjectId)result=await sb.from('sf_projects').update(payload).eq('id',currentProjectId).eq('user_id',currentUser.id);else result=await sb.from('sf_projects').insert(payload).select('id').single();if(result.error){toast(result.error.message,'error');return}if(!currentProjectId&&result.data?.id)currentProjectId=result.data.id;toast('Project saved.');try{await loadProjects()}catch{}}
q('#saveProject').onclick=saveProjectV06;

try{openProject=function(id,projects){const p=projects.find(x=>String(x.id)===String(id));if(!p)return;try{snapshot()}catch{};canvas.innerHTML=p.project_json?.svg||'<rect width="1600" height="1000" fill="#fff" data-canvas-bg="1"/>';const w=+(p.project_json?.canvas?.width||p.canvas_width||1600),h=+(p.project_json?.canvas?.height||p.canvas_height||1000);canvas.setAttribute('viewBox',`0 0 ${w} ${h}`);canvas.dataset.canvasWidth=w;canvas.dataset.canvasHeight=h;q('#projectTitle').value=p.title;q('#studioDomain').value=p.domain||'biological';try{renderDomain();currentProjectId=p.id;selectObject(null)}catch{};updateCanvasNote();toast('Project opened.')}}catch{}

function cleanForExport(transparent=false){try{selectObject(null)}catch{};const clone=canvas.cloneNode(true);clone.querySelectorAll('.selection-outline').forEach(x=>x.remove());clone.querySelectorAll('.selected,.multi-selected').forEach(x=>x.classList.remove('selected','multi-selected'));const {w,h}=dims();clone.setAttribute('xmlns','http://www.w3.org/2000/svg');clone.setAttribute('width',w);clone.setAttribute('height',h);let bg=clone.querySelector(':scope > rect[data-canvas-bg],:scope > rect');if(bg&&transparent)bg.setAttribute('fill','none');const meta=document.createElementNS('http://www.w3.org/2000/svg','metadata');meta.textContent=JSON.stringify({software:'SciFigure Commons',version:APP_VERSION,title:q('#projectTitle').value||'',exported:new Date().toISOString(),canvas:{width:w,height:h}});clone.insertBefore(meta,clone.firstChild);return {clone,w,h}}
function safeName(ext){return (q('#projectTitle').value.trim()||'scientific-figure').replace(/[^a-z0-9-_]+/gi,'-').replace(/^-|-$/g,'')+'.'+ext}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},700)}
function exportSvgV06(){const {clone}=cleanForExport(false),xml='<?xml version="1.0" encoding="UTF-8"?>\n'+new XMLSerializer().serializeToString(clone);downloadBlob(new Blob([xml],{type:'image/svg+xml;charset=utf-8'}),safeName('svg'))}
function exportPngV06(transparent=false,scale=2){const {clone,w,h}=cleanForExport(transparent);clone.setAttribute('width',w*scale);clone.setAttribute('height',h*scale);const xml=new XMLSerializer().serializeToString(clone),url=URL.createObjectURL(new Blob([xml],{type:'image/svg+xml'})),img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=w*scale;c.height=h*scale;const ctx=c.getContext('2d');if(!transparent){ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height)}ctx.drawImage(img,0,0,c.width,c.height);URL.revokeObjectURL(url);c.toBlob(blob=>blob&&downloadBlob(blob,safeName(transparent?'transparent.png':'png')),'image/png')};img.onerror=()=>{URL.revokeObjectURL(url);toast('PNG rendering failed. Try SVG export.','error')};img.src=url}
try{exportSVG=exportSvgV06;exportPNG=()=>exportPngV06(false,2)}catch{}
q('#exportSvg')&&(q('#exportSvg').onclick=exportSvgV06);q('#exportPng')&&(q('#exportPng').onclick=()=>exportPngV06(false,2));q('#v05Transparent')&&(q('#v05Transparent').onclick=()=>exportPngV06(true,2));

/* ---------- Registration recovery ---------- */
const reg=q('#registerForm');if(reg){reg.onsubmit=async e=>{e.preventDefault();const f=new FormData(reg),msg=q('#authMessage');const profile={full_name:String(f.get('full_name')||''),account_type:String(f.get('account_type')||''),institution:String(f.get('institution')||''),discipline:String(f.get('discipline')||''),scientific_id_type:String(f.get('scientific_id_type')||''),scientific_id_value:String(f.get('scientific_id_value')||''),scientific_id_url:safeUrl(String(f.get('scientific_id_url')||''))||null};msg.textContent='Creating secure account…';const {data,error}=await sb.auth.signUp({email:f.get('email'),password:f.get('password'),options:{data:{sf_applicant:true}}});if(error){msg.textContent=error.message;return}if(data.session&&data.user){const {error:pe}=await sb.from('sf_profiles').insert({user_id:data.user.id,...profile});msg.textContent=pe?pe.message:'Registration submitted for administrator verification.'}else{localStorage.setItem('sf_pending_profile',JSON.stringify(profile));msg.textContent='Account created. Confirm your email, then sign in; your verification profile will be completed automatically.'}}}
async function finishPendingProfile(){let raw=localStorage.getItem('sf_pending_profile');if(!raw||!currentUser||currentProfile)return;try{const profile=JSON.parse(raw);const {error}=await sb.from('sf_profiles').insert({user_id:currentUser.id,...profile});if(!error){localStorage.removeItem('sf_pending_profile');currentProfile={user_id:currentUser.id,verification_status:'pending',...profile};q('#accessStatus').textContent='Pending verification';toast('Verification profile completed.')}}catch{}}
try{const oldRefresh=refreshSession;refreshSession=async function(){await oldRefresh();await finishPendingProfile()}}catch{}

/* ---------- Harden remote SVG import ---------- */
function installSafeImporter(root=document){const btn=root.querySelector?.('#v05DoImport');if(!btn||btn.dataset.safe==='1')return;btn.dataset.safe='1';btn.onclick=async()=>{const url=safeUrl(q('#v05SvgUrl')?.value.trim()),source=(q('#v05SvgSource')?.value||'').trim(),license=(q('#v05SvgLicense')?.value||'').trim(),attr=(q('#v05SvgAttr')?.value||'').trim(),status=q('#v05ImportStatus');if(!url||!license){status.textContent='Use an HTTPS SVG URL and provide its license.';return}status.textContent='Validating SVG…';try{const r=await fetch(url,{mode:'cors',credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw new Error('HTTP '+r.status);const txt=await r.text();if(txt.length>1_500_000)throw new Error('SVG is too large for browser import.');const doc=new DOMParser().parseFromString(txt,'image/svg+xml');if(doc.querySelector('parsererror')||doc.documentElement.nodeName.toLowerCase()!=='svg')throw new Error('Invalid SVG file.');doc.querySelectorAll('script,foreignObject,iframe,object,embed,a,style').forEach(x=>x.remove());doc.querySelectorAll('*').forEach(el=>{[...el.attributes].forEach(a=>{const val=a.value||'';if(/^on/i.test(a.name)||/javascript:|data:text\/html|url\s*\(/i.test(val)||(a.name==='href'||a.name.endsWith(':href'))&&val&&!val.startsWith('#'))el.removeAttribute(a.name)})});const src=doc.documentElement,g=makeObject('external-svg',220,180);g.dataset.source=source;g.dataset.license=license;g.dataset.attribution=attr;g.dataset.sourceUrl=url;const inner=svgEl('g');[...src.childNodes].forEach(n=>inner.appendChild(document.importNode(n,true)));g.appendChild(inner);let bb;try{bb=inner.getBBox()}catch{};g.appendChild(outline((bb?.x||0)-10,(bb?.y||0)-10,(bb?.width||400)+20,(bb?.height||300)+20));addToCanvas(g);status.textContent='Imported safely. License metadata is attached to this object.';toast('Licensed SVG inserted.')}catch(err){status.textContent='Import failed: '+err.message}}}
const importerObserver=new MutationObserver(ms=>ms.forEach(m=>m.addedNodes.forEach(n=>{if(n.nodeType===1)installSafeImporter(n)})));importerObserver.observe(document.body,{childList:true,subtree:true});installSafeImporter();

/* ---------- Quality, accessibility and integrity audit ---------- */
function luminance(hex){const m=String(hex).match(/^#([0-9a-f]{6})$/i);if(!m)return null;const v=[0,2,4].map(i=>parseInt(m[1].slice(i,i+2),16)/255).map(x=>x<=.03928?x/12.92:Math.pow((x+.055)/1.055,2.4));return .2126*v[0]+.7152*v[1]+.0722*v[2]}
function contrast(a,b){const l1=luminance(a),l2=luminance(b);if(l1==null||l2==null)return null;return (Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05)}
function qualityData(){const os=objects(),texts=qa('#figureCanvas .sf-object text'),external=os.filter(x=>x.dataset.kind==='external-svg');const issues=[],good=[];if(!os.length)issues.push('Canvas is empty.');if(os.length>22)issues.push('High visual density; consider reducing objects.');else if(os.length>0)good.push('Object count is manageable.');const tiny=texts.filter(t=>+(t.getAttribute('font-size')||0)<22).length;if(tiny)issues.push(`${tiny} text label(s) may be too small for publication.`);else if(texts.length)good.push('Text sizes are generally readable.');const unl=external.filter(x=>!x.dataset.license).length;if(unl)issues.push(`${unl} external asset(s) lack license metadata.`);else if(external.length)good.push('External asset licenses are recorded.');const c=contrast(q('#elementColor')?.value,'#ffffff');if(c&&c<3)issues.push('Primary color has low contrast against white.');else if(c)good.push('Primary color contrast is acceptable.');const {w,h}=dims();os.forEach(g=>{const x=+(g.dataset.x||0),y=+(g.dataset.y||0);if(x<-40||y<-40||x>w+40||y>h+40)issues.push('At least one object is outside the visible canvas.')});const score=Math.max(20,100-issues.length*13-(os.length>28?10:0));return {score,issues:[...new Set(issues)],good:[...new Set(good)],objects:os.length,texts:texts.length,external:external.length}}
function runQualityAudit(silent=false){const d=qualityData();const report=q('#v04Report');if(report)report.innerHTML=`<div class="sf-score"><b>${d.score}</b><span>/100<br>Figure quality</span></div><strong>${d.objects} objects • ${d.texts} labels • ${d.external} external assets</strong>${d.issues.length?`<ul>${d.issues.map(x=>`<li>${escapeHtml(x)}</li>`).join('')}</ul>`:'<p>No major automated warnings.</p>'}<small>Automated checks assess layout and metadata, not scientific correctness.</small>`;if(!silent)toast(`Figure quality score: ${d.score}/100`);return d}

/* ---------- Self-test ---------- */
async function selfTest(){const checks=[];const add=(name,ok,detail='')=>checks.push({name,ok,detail});add('Canvas engine',!!canvas);add('Object model',typeof makeObject==='function'&&typeof addToCanvas==='function');add('Undo history',Array.isArray(history));add('Supabase client',typeof sb?.from==='function');add('Save control',!!q('#saveProject'));add('SVG export',!!q('#exportSvg'));add('PNG export',!!q('#exportPng'));add('Copilot',!!q('#sfCopilot'));const ids=qa('[id]').map(x=>x.id),dups=ids.filter((x,i)=>ids.indexOf(x)!==i);add('Unique DOM IDs',dups.length===0,dups.length?dups.join(', '):'');try{const {error}=await sb.from('sf_assets').select('id',{head:true,count:'exact'}).limit(1);add('Database reachability',!error,error?.message||'')}catch(e){add('Database reachability',false,e.message)}showDiagnostics(checks)}
function showDiagnostics(checks){let m=q('#sfDiag');if(!m){m=document.createElement('div');m.id='sfDiag';m.className='sf-modal';document.body.appendChild(m)}const pass=checks.filter(x=>x.ok).length;m.innerHTML=`<div class="sf-modal-card"><div class="sf-modal-head"><div><span class="eyebrow">SYSTEM DIAGNOSTICS</span><h2>SciFigure v${APP_VERSION}</h2></div><button data-close>×</button></div><div class="sf-test-summary"><b>${pass}/${checks.length}</b><span>checks passed</span></div><div class="sf-test-list">${checks.map(x=>`<div class="${x.ok?'pass':'fail'}"><span>${x.ok?'✓':'!'}</span><b>${escapeHtml(x.name)}</b><small>${escapeHtml(x.detail||'')}</small></div>`).join('')}</div></div>`;m.querySelector('[data-close]').onclick=()=>m.remove();m.onclick=e=>{if(e.target===m)m.remove()}}

/* ---------- Local recovery ---------- */
let lastRecovery='';setInterval(()=>{try{const state=JSON.stringify({title:q('#projectTitle').value,domain:q('#studioDomain').value,viewBox:canvas.getAttribute('viewBox'),svg:canvas.innerHTML,at:new Date().toISOString()});if(state!==lastRecovery){localStorage.setItem('sf_local_recovery',state);lastRecovery=state}}catch{}},15000);

/* ---------- UI wiring ---------- */
qa('[data-pro]').forEach(b=>b.onclick=()=>{const a=b.dataset.pro;if(a==='new')newFigure();if(a==='smart'){q('#sfCopilotPrompt')?.focus();q('#sfCopilot')?.scrollIntoView({behavior:'smooth',block:'center'})}if(a==='audit')runQualityAudit();if(a==='arrange')autoArrange();if(a==='test')selfTest()});
function updateCanvasNote(){const {w,h}=dims(),note=q('.canvas-note');if(note)note.textContent=`Publication canvas: ${w} × ${h} • vector-first • SVG recommended for journal artwork`}
const vbObs=new MutationObserver(updateCanvasNote);vbObs.observe(canvas,{attributes:true,attributeFilter:['viewBox']});updateCanvasNote();

function toast(message,type='ok'){let t=q('#sfToast');if(!t){t=document.createElement('div');t.id='sfToast';document.body.appendChild(t)}t.className='sf-toast '+type;t.textContent=message;requestAnimationFrame(()=>t.classList.add('show'));clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2600)}

/* Initial cleanup */
qa('.left-rail>.rail-block b,.right-rail>.rail-block b').forEach(b=>{b.textContent=b.textContent.replace(/\bv0\.[45]\b/ig,'').trim()});
setTimeout(()=>{sanitizeDynamicUrls();runQualityAudit(true)},250);
})();