-- JBR Global Discovery & Research Network
-- Production starter schema for Supabase/PostgreSQL.
-- Review RLS, privacy, ethics and institutional governance before production use.

create extension if not exists pgcrypto;

create table if not exists public.researchers (
  id uuid primary key default gen_random_uuid(),
  user_id uuid unique,
  full_name text not null,
  title text,
  institution text,
  country text,
  orcid text,
  profile_url text,
  biography text,
  verified boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.expertise (
  id bigint generated by default as identity primary key,
  name text unique not null
);

create table if not exists public.researcher_expertise (
  researcher_id uuid references public.researchers(id) on delete cascade,
  expertise_id bigint references public.expertise(id) on delete cascade,
  level text check (level in ('working','advanced','expert')),
  primary key (researcher_id, expertise_id)
);

create table if not exists public.research_ideas (
  id uuid primary key default gen_random_uuid(),
  submitted_by uuid references public.researchers(id),
  title text not null,
  primary_domain text not null,
  research_gap text not null,
  multidisciplinary_need text not null,
  status text not null default 'submitted' check (status in ('submitted','screening','needs_revision','approved','merged','rejected')),
  private_submission boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.discovery_challenges (
  id uuid primary key default gen_random_uuid(),
  public_id text unique not null,
  title text not null,
  summary text not null,
  research_gap text not null,
  hypothesis text,
  status text not null default 'concept_development' check (status in ('concept_development','open','team_formation','active','validation','completed','paused')),
  lead_researcher_id uuid references public.researchers(id),
  is_public boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.challenge_expertise (
  challenge_id uuid references public.discovery_challenges(id) on delete cascade,
  expertise_id bigint references public.expertise(id) on delete cascade,
  requirement text,
  slots integer,
  primary key (challenge_id, expertise_id)
);

create table if not exists public.applications (
  id uuid primary key default gen_random_uuid(),
  challenge_id uuid references public.discovery_challenges(id) on delete cascade,
  researcher_id uuid references public.researchers(id),
  proposed_role text not null,
  contribution text not null,
  status text not null default 'submitted' check (status in ('submitted','under_review','shortlisted','accepted','declined','withdrawn')),
  created_at timestamptz not null default now()
);

create table if not exists public.projects (
  id uuid primary key default gen_random_uuid(),
  challenge_id uuid references public.discovery_challenges(id),
  project_code text unique not null,
  title text not null,
  status text not null default 'planning' check (status in ('planning','protocol','active','analysis','validation','manuscript','completed','paused')),
  created_at timestamptz not null default now()
);

create table if not exists public.project_members (
  project_id uuid references public.projects(id) on delete cascade,
  researcher_id uuid references public.researchers(id) on delete cascade,
  project_role text not null,
  credit_roles text[],
  joined_at timestamptz not null default now(),
  primary key (project_id, researcher_id)
);

create table if not exists public.milestones (
  id uuid primary key default gen_random_uuid(),
  project_id uuid references public.projects(id) on delete cascade,
  title text not null,
  due_date date,
  status text not null default 'planned' check (status in ('planned','active','blocked','completed')),
  notes text
);

create table if not exists public.audit_events (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  entity_type text not null,
  entity_id text not null,
  action text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.researchers enable row level security;
alter table public.research_ideas enable row level security;
alter table public.discovery_challenges enable row level security;
alter table public.applications enable row level security;
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.milestones enable row level security;

create policy "public_can_read_public_challenges"
on public.discovery_challenges
for select
using (is_public = true);

-- Add authenticated researcher/admin policies only after JBR roles and governance are approved.
